apiVersion: apps/v1
kind: Deployment
metadata:
  name: management-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: management-service
  template:
    metadata:
      labels:
        app: management-service
    spec:
      containers:
        - name: management-service
          image: openjournalismregistry.azurecr.io/management-service:latest
          ports:
            - containerPort: 80
